import { previewTextRow, type PreviewScenarioSnapshot } from './message';

/*
Every markdown construct an agent writes often, in one reply: the heading
ladder, fences in several languages (including one whose lines are far wider
than the pane), a table wider than the column, GitHub's blockquote alerts,
colors, bare file paths in prose, and nested lists.
*/
const RICH_MARKDOWN = [
  '# Transcript rendering review',
  '',
  'The shared rules now cover every construct below, so a reply reads the same in both renderers.',
  '',
  '## Where the rules live',
  '',
  'Turn boundaries are decided in packages/shared/session-chat-presentation/turns.ts:173, and the native renderer reads the same result from apps/desktop/src/app/native_chat/transcript.rs:88:14. Nothing decides a boundary twice.',
  '',
  '### Palette',
  '',
  'The tone badges use `#7cc4a4` for a completed action, `#e0a458` for a warning, and `#f26d6d` for a failure. Links keep the accent `#4f9cf9` in both themes.',
  '',
  '#### Checklist',
  '',
  '1. Prose and inline code',
  '   - Wrapping matches at 100% zoom',
  '   - Selection copies the visible words in order',
  '     - Including across an explicit line break',
  '2. Block content',
  '   - Fences keep their language chip',
  '     1. `ts`, `rust`, `zig`, `bash`, `json`',
  '     2. One fence with lines far wider than the pane',
  '   - Tables scroll sideways instead of squeezing their columns',
  '3. Callouts',
  '   - All five GitHub alert kinds',
  '',
  '> The same data should produce the same visible state, whichever renderer drew it.',
  '',
  '> [!NOTE]',
  '> Reasoning rows keep their own text as the disclosure heading, so verbose mode never produces a column of identical labels.',
  '',
  '> [!TIP]',
  '> Simple mode hides command previews and shows only the tool-call count until you expand the row.',
  '',
  '> [!IMPORTANT]',
  '> A harness-injected row never settles the response above it. Both renderers must honour that or a live turn folds mid-stream.',
  '',
  '> [!WARNING]',
  '> Changing the fold rules changes scroll restoration too, because a folded turn is one row instead of twenty.',
  '',
  '> [!CAUTION]',
  '> Never rewrite a whole transcript file from a cached copy; another session may have appended to it since the read.',
  '',
  '```ts',
  'export function foldChatTranscript(messages: readonly SessionChatMessage[]): SessionChatMessage[] {',
  '  return foldSessionChatToolMessages(messages, (message) => sessionChatSuppressedTurnLabel(message) !== null);',
  '}',
  '```',
  '',
  '```rust',
  'pub fn turn_rows(&self, working: bool) -> Vec<TranscriptRow> {',
  '    let items = completed_work_render_items(&self.messages, working);',
  '    items.iter().map(TranscriptRow::from_item).collect()',
  '}',
  '```',
  '',
  '```zig',
  'pub fn appendClientInputMessages(self: *Loop, bytes: []const u8) !void {',
  '    if (std.mem.indexOf(u8, bytes, ZMX_REFRESH)) |_| try self.refresh();',
  '}',
  '```',
  '',
  '```bash',
  'bun run typecheck && bun run desktop:typecheck',
  '```',
  '',
  '```json',
  '{ "sessionChatUseGpui": false, "sessionChatVerboseMode": false, "sessionChatZoomPercent": 100 }',
  '```',
  '',
  'One fence deliberately refuses to wrap, so the horizontal scroll and the copy control can be compared:',
  '',
  '```python',
  'RENDER_ORDER = ["fork-boundary", "user-prompt", "reasoning", "tool-run", "file-change-card", "question-exchange", "agent-message", "status-row", "final-reply", "queued-prompt", "startup-delivery", "terminal-tool-row"]',
  'assert all(isinstance(row, str) for row in RENDER_ORDER), "every render row is named by a string, and this assertion line is long on purpose so the fence has to scroll sideways"',
  '```',
  '',
  '## Row inventory',
  '',
  '| Row | Owner | Folds with the turn | Keyboard | Native status | Notes |',
  '| --- | --- | --- | --- | --- | --- |',
  '| User prompt | transcript | no | Enter to send | done | Carries attachments and queued state |',
  '| Reasoning | transcript | yes | Space toggles | done | Heading is the reasoning text itself |',
  '| Tool run | transcript | yes | Space toggles | in progress | Folds to "+N previous tool calls" |',
  '| File change card | transcript | hoisted | Click toggles | in progress | Grouped as "N files changed" |',
  '| Question exchange | tool pair | never | Space toggles | not started | Conversation, not work |',
  '| Status row | harness | yes | none | done | One row per completed action |',
  '| Terminal tool | screen | never | none | not started | Retires when the transcript catches up |',
  '',
  'Anything not in that table renders through the ordinary markdown path and needs no special rule.',
].join('\n');

/** One reply carrying the markdown constructs agents write most often. */
export function richMarkdownPreviewScenario(): PreviewScenarioSnapshot {
  return {
    messages: [
      previewTextRow(
        'rich-1',
        'user',
        0,
        'Write up the transcript rendering review with the full formatting: headings, alerts, a wide table, code in several languages, and the colors.'
      ),
      previewTextRow('rich-2', 'assistant', 18, RICH_MARKDOWN),
    ],
  };
}
