// Harness-injected turn classifier (upstream chat spec §9.1 port — tag and
// prefix constants verbatim).
//
// Design law (do not "improve" this): match only tags OBSERVED from
// harnesses, never a broad kebab shape. A real prompt starting with a custom
// <my-element> or a Grok <user_query> envelope is a genuine user turn;
// misclassifying it hides the turn. Note <channel> is only matched in its
// attributed `<channel source=` form — a bare <channel> is a real RSS/XML
// paste.
//
// Second law: a matched turn is SUPPRESSED, not deleted. Everything the
// terminal itself prints (task notifications, local command output, an
// interrupt notice, a continuation summary, messages from other sessions)
// renders as a one-line collapsed marker that expands to the full text —
// deleting them is exactly what reads as "chat is missing messages". Only the
// records the terminal never shows either (system reminders, hook plumbing)
// stay hidden.

import type { SessionChatMessage } from "../../shared/session-chat";

const LEADING_TAG_NAME = /^<([a-z][a-z0-9-]*)(?:[\s>]|$)/;
const MARKUP_TAG = /<\/?[a-z][a-z0-9-]*(?:\s[^>]*)?>/gi;

/*
 * /compact's local-command stdout is just a dim "Compacted" wrapped in ANSI
 * style codes; readers deserve "Compaction completed" instead of a generic
 * "Local command output" marker. Deliberately lenient: strip SGR sequences
 * (with or without the ESC byte surviving transcript encoding), fold
 * whitespace, and accept the wording variants harnesses have used.
 */
const ANSI_STYLE_SEQUENCE = /(?:\u001b|\u009b)?\[[0-9;]{1,8}m/g;
const COMPACTION_OUTPUT =
  /^compact(?:ed|ing|ion)\b(?:\s+(?:is\s+)?(?:complete[d]?|done|finished|successful(?:ly)?))?\s*[.!…]*$/i;

function isCompactionCommandOutput(text: string): boolean {
  const body = sessionChatSuppressedTurnBody(text)
    .replace(ANSI_STYLE_SEQUENCE, "")
    .replace(/\s+/g, " ")
    .trim();
  return COMPACTION_OUTPUT.test(body);
}

/** Harness tags that render as a collapsed, expandable marker. */
const COLLAPSED_TAG_LABELS: Readonly<Record<string, string>> = {
  "agent-message": "Message from another session",
  "bash-input": "Local command",
  "bash-stderr": "Local command output",
  "bash-stdout": "Local command output",
  "command-args": "Slash command",
  "command-message": "Slash command",
  "command-name": "Slash command",
  "cross-session-message": "Message from another session",
  "local-command-caveat": "Local command output",
  "local-command-stderr": "Local command output",
  "local-command-stdout": "Local command output",
  "task-notification": "Task notification",
  "teammate-message": "Message from another session",
  "user-memory-input": "Memory note",
};

/** Harness tags the agent's own TUI never prints either — stay hidden. */
const HIDDEN_TAG_NAMES: ReadonlySet<string> = new Set([
  "fork-boilerplate",
  "mcp-polling-update",
  "mcp-resource-update",
  "system-reminder",
  "user-prompt-submit-hook",
]);

const COLLAPSED_PREFIX_LABELS: readonly (readonly [string, string])[] = [
  ["<channel source=", "Message from another session"],
  ["[request interrupted", "Interrupted"],
  ["a message arrived from ", "Message from another session"],
  ["another claude session sent a message", "Message from another session"],
  ["no response requested.", "Message from another session"],
  [
    "caveat: the messages below were generated by the user while running local commands",
    "Local command output",
  ],
  [
    "this session is being continued from a previous conversation",
    "Session continued from a previous conversation",
  ],
];

export const SESSION_CHAT_KNOWN_HARNESS_TAG_NAMES: ReadonlySet<string> = new Set([
  ...Object.keys(COLLAPSED_TAG_LABELS),
  ...HIDDEN_TAG_NAMES,
]);

export const SESSION_CHAT_HARNESS_INJECTED_TURN_PREFIXES: readonly string[] =
  COLLAPSED_PREFIX_LABELS.map(([prefix]) => prefix);

export function isKnownHarnessInjectedUserTurnText(text: string): boolean {
  return harnessInjectedTurnLabel(text) !== null;
}

/**
 * The marker label for a harness-injected turn, "" when the turn is one the
 * terminal never shows either, or null when it is a genuine user turn.
 */
function harnessInjectedTurnLabel(text: string): string | null {
  const normalized = text.trim().toLowerCase();
  if (normalized.length === 0) {
    return null;
  }
  const tagName = LEADING_TAG_NAME.exec(normalized)?.[1];
  if (tagName) {
    const label = COLLAPSED_TAG_LABELS[tagName];
    if (label) {
      return label;
    }
    if (HIDDEN_TAG_NAMES.has(tagName)) {
      return "";
    }
  }
  for (const [prefix, label] of COLLAPSED_PREFIX_LABELS) {
    if (normalized.startsWith(prefix)) {
      return label;
    }
  }
  return null;
}

export function sessionChatMessageText(message: SessionChatMessage): string {
  return message.blocks
    .filter((block) => block.type === "text")
    .map((block) => block.text)
    .join("")
    .trim();
}

/** Text left once the harness markup is removed — "" ⇒ nothing to expand. */
export function sessionChatSuppressedTurnBody(text: string): string {
  return text.replace(MARKUP_TAG, "").trim();
}

export type SessionChatSuppressedTurn =
  /** Never surfaced: the agent's own TUI does not print it either. */
  | { kind: "hidden" }
  /** One-line marker that expands to the full text on click. */
  | { kind: "collapsed"; label: string };

export function classifySessionChatSuppressedTurn(
  message: SessionChatMessage,
): SessionChatSuppressedTurn | null {
  if (message.role !== "user" && message.role !== "system") {
    return null;
  }
  if (
    message.blocks.some(
      (block) => block.type === "tool-call" || block.type === "tool-result",
    )
  ) {
    return null;
  }
  const text = sessionChatMessageText(message);
  const label = harnessInjectedTurnLabel(text);
  if (label === null) {
    return null;
  }
  if (label === "" || sessionChatSuppressedTurnBody(text).length === 0) {
    // Hidden class, or pure markup with no readable content.
    return { kind: "hidden" };
  }
  if (label === "Local command output" && isCompactionCommandOutput(text)) {
    return { kind: "collapsed", label: "Compaction completed" };
  }
  return { kind: "collapsed", label };
}

export function isSessionChatNoiseMessage(message: SessionChatMessage): boolean {
  return classifySessionChatSuppressedTurn(message) !== null;
}

/** True only for turns that must not reach the list at all. */
export function isSessionChatHiddenMessage(message: SessionChatMessage): boolean {
  return classifySessionChatSuppressedTurn(message)?.kind === "hidden";
}

/** The collapsed-marker label, or null when the turn renders normally. */
export function sessionChatSuppressedTurnLabel(
  message: SessionChatMessage,
): string | null {
  const suppressed = classifySessionChatSuppressedTurn(message);
  return suppressed?.kind === "collapsed" ? suppressed.label : null;
}

export function stripSessionChatNoiseMessages(
  messages: readonly SessionChatMessage[],
): SessionChatMessage[] {
  return messages.filter((message) => !isSessionChatNoiseMessage(message));
}

/** Drop only the never-surfaced turns; collapsed markers stay in the list. */
export function dropSessionChatHiddenMessages(
  messages: readonly SessionChatMessage[],
): SessionChatMessage[] {
  return messages.filter((message) => !isSessionChatHiddenMessage(message));
}
