// Noise filter (orca §9.1 port — constants verbatim).
//
// Design law (do not "improve" this): match only tags OBSERVED from
// harnesses, never a broad kebab shape. A real prompt starting with a custom
// <my-element> or a Grok <user_query> envelope is a genuine user turn;
// misclassifying it hides the turn. Note <channel> is only matched in its
// attributed `<channel source=` form — a bare <channel> is a real RSS/XML
// paste.

import type { SessionChatMessage } from "../../shared/session-chat";

const LEADING_TAG_NAME = /^<([a-z][a-z0-9-]*)(?:[\s>]|$)/;

export const SESSION_CHAT_KNOWN_HARNESS_TAG_NAMES: ReadonlySet<string> = new Set([
  "agent-message",
  "bash-input",
  "bash-stderr",
  "bash-stdout",
  "command-args",
  "command-message",
  "command-name",
  "cross-session-message",
  "fork-boilerplate",
  "local-command-caveat",
  "local-command-stderr",
  "local-command-stdout",
  "mcp-polling-update",
  "mcp-resource-update",
  "system-reminder",
  "task-notification",
  "teammate-message",
  "user-memory-input",
  "user-prompt-submit-hook",
]);

export const SESSION_CHAT_HARNESS_INJECTED_TURN_PREFIXES: readonly string[] = [
  "<channel source=",
  "[request interrupted",
  "a message arrived from ",
  "another claude session sent a message",
  "no response requested.",
  "caveat: the messages below were generated by the user while running local commands",
  "this session is being continued from a previous conversation",
];

export function isKnownHarnessInjectedUserTurnText(text: string): boolean {
  const normalized = text.trim().toLowerCase();
  if (normalized.length === 0) {
    return false;
  }
  const tagName = LEADING_TAG_NAME.exec(normalized)?.[1];
  if (tagName && SESSION_CHAT_KNOWN_HARNESS_TAG_NAMES.has(tagName)) {
    return true;
  }
  return SESSION_CHAT_HARNESS_INJECTED_TURN_PREFIXES.some((prefix) =>
    normalized.startsWith(prefix),
  );
}

export function sessionChatMessageText(message: SessionChatMessage): string {
  return message.blocks
    .filter((block) => block.type === "text")
    .map((block) => block.text)
    .join("")
    .trim();
}

export function isSessionChatNoiseMessage(message: SessionChatMessage): boolean {
  if (message.role !== "user" && message.role !== "system") {
    return false;
  }
  if (
    message.blocks.some(
      (block) => block.type === "tool-call" || block.type === "tool-result",
    )
  ) {
    return false;
  }
  return isKnownHarnessInjectedUserTurnText(sessionChatMessageText(message));
}

export function stripSessionChatNoiseMessages(
  messages: readonly SessionChatMessage[],
): SessionChatMessage[] {
  return messages.filter((message) => !isSessionChatNoiseMessage(message));
}
