/**
 * Writes a small, entirely invented recording to `/tmp/gx-chat/synthetic.jsonl`.
 *
 * Usage: `bun tooling/gx-chat-core/synthetic-recording.ts`
 *
 * Real recordings are the user's conversation, so they never leave `/tmp` and cannot be shared
 * between agents. This one is built from the sample-conversation fixtures the Chat Lab already
 * ships (`packages/shared/session-chat-preview/`), which means it can be regenerated by anyone,
 * at any time, on a machine that has never opened a chat. It walks the brain through the parts
 * of the transcript that are hardest to port: a user message, an agent message streamed in
 * pieces with markdown and a fenced code block, a tool group whose result is a patch, a
 * question with options, an approval, a queued prompt, and an error notice.
 *
 * The world it runs in is scripted, not sampled: the clock advances a fixed step per call, the
 * random source is a seeded generator and the ids are a counter, so two generations produce a
 * byte-identical file and the replay of it is reproducible.
 *
 * The answers to the brain's own requests come from `ChatPreviewBackend`, the same simulated
 * server the Chat Lab uses. It is used only as an answer table: the recording carries the real
 * `resolve` calls, so replaying it exercises the ordinary request path rather than a preview
 * mode the Rust port will never have.
 */
import { mkdirSync, writeFileSync } from 'node:fs';

import { ChatPreviewBackend } from '@/packages/shared/session-chat-preview/backend';
import { DEFAULT_CHAT_PREVIEW } from '@/packages/shared/session-chat-preview/fixture';
import {
  previewCall,
  previewResult,
  previewRow,
  previewStamp,
  previewTextRow,
  PREVIEW_START_MS,
} from '@/packages/shared/session-chat-preview/message';
import type { GxserverReadSessionChatResult, SessionChatMessage } from '@/packages/shared/session-chat';
import {
  nativeChatReplayHash,
  type NativeChatReplayDriver,
  type NativeChatReplayKind,
} from '@/packages/shared/session-chat-controller/native-host-replay';
import { loadChatBrain, settle } from './brain';
import { composerAnswer, RECORDING_ROOT, serializeHeader, serializeRecord, type ReplayRecord } from './recording';

const CLOCK_START = PREVIEW_START_MS;
/** How far the invented clock moves between two calls, enough for the rules' short timers. */
const CLOCK_STEP_MS = 25;
const PROJECT_ID = 'gx-synthetic-project';
const SESSION_ID = 'gx-synthetic-session';

/* -------------------------------------------------------------------------- the invented world */

/**
 * Records every call the way the app's recorder does, but from a world with no real clock, no
 * entropy and no operating system: the same script always writes the same bytes.
 */
class SyntheticWorld implements NativeChatReplayDriver {
  readonly lines: string[] = [];
  private open: ReplayRecord | null = null;
  private sequence = 0;
  private ms = CLOCK_START;
  private randomState = 0x2f6e2b1;
  private uuidCount = 0;
  /**
   * Reads the generator itself makes are not the brain's. The answer table stamps its replies
   * with the clock, and on a replay those stamps arrive inside a recorded `resolve` instead,
   * so counting them here would leave every later record one read short.
   */
  private suspended = 0;

  /** Runs the generator's own work with its reads left out of the open record. */
  async outside<T>(work: () => Promise<T>): Promise<T> {
    this.suspended += 1;
    try {
      return await work();
    } finally {
      this.suspended -= 1;
    }
  }

  private get recording(): ReplayRecord | null {
    return this.suspended ? null : this.open;
  }

  begin(kind: NativeChatReplayKind, method: string, args: readonly unknown[]): void {
    this.flush();
    this.ms += CLOCK_STEP_MS;
    this.sequence += 1;
    this.open = { n: this.sequence, k: kind, m: method, ms: this.ms, a: args as unknown[], c: [], r: [], u: [] };
  }

  clock(): number {
    this.recording?.c!.push(this.ms);
    return this.ms;
  }

  random(): number {
    // A 32-bit xorshift, so the sequence is reproducible without a dependency.
    let state = this.randomState;
    state ^= state << 13;
    state ^= state >>> 17;
    state ^= state << 5;
    this.randomState = state >>> 0;
    const value = this.randomState / 0x100000000;
    this.recording?.r!.push(value);
    return value;
  }

  uuid(): string {
    this.uuidCount += 1;
    const value = `00000000-0000-4000-8000-${String(this.uuidCount).padStart(12, '0')}`;
    this.recording?.u!.push(value);
    return value;
  }

  result(hash: string, length: number): void {
    if (!this.open) return;
    this.open.hash = hash;
    this.open.len = length;
  }

  flush(): void {
    if (!this.open) return;
    this.lines.push(serializeRecord(this.open));
    this.open = null;
  }
}

/* ------------------------------------------------------------------------- the sample transcript */

const MARKDOWN_REPLY = [
  '## Proposed change',
  '',
  'Keep the transcript rules shared and let each renderer own its layout.',
  '',
  '- **One set of rules** for messages, tools, and questions.',
  '- **Two renderers** for layout and input.',
  '- Drafts survive a switch between them.',
  '',
  '```ts',
  'export function greeting(name: string) {',
  '  return `Hello, ${name}!`;',
  '}',
  '```',
  '',
  '> The same conversation should produce the same visible state.',
  '',
  '| Area | Status |',
  '| --- | --- |',
  '| Messages | Ready |',
  '| Composer | Ready |',
].join('\n');

const PATCH_RESULT = [
  '*** Begin Patch',
  '*** Update File: packages/shared/session-chat-presentation/transcript.ts',
  '@@ -13,7 +13,7 @@',
  ' export function normalizeChatTranscript(messages: readonly SessionChatMessage[]) {',
  '   return dropSessionChatHiddenMessages(',
  '-    orderSessionChatMessages(messages)',
  '+    normalizeSessionChatLocalCommandMessages(orderSessionChatMessages(messages))',
  '   );',
  ' }',
  '*** End Patch',
].join('\n');

/** The rows the recording streams in, oldest first. */
function transcript(): SessionChatMessage[] {
  return [
    previewTextRow('s1', 'user', 10, 'Can you review the transcript rules and apply the fix?'),
    previewTextRow('s2', 'reasoning', 20, 'The rules should own behaviour; each renderer owns layout and input.'),
    previewRow('s3', 'tool', 30, [
      previewCall('Read', { file_path: '/sample/project/packages/shared/session-chat-presentation/transcript.ts' }),
      previewResult('export function normalizeChatTranscript(messages) {\n  return messages;\n}'),
      previewCall('Grep', { pattern: 'normalizeChatTranscript' }),
      previewResult('packages/shared/session-chat-presentation/transcript.ts\npackages/core-ui/chat/list.tsx'),
    ]),
    previewTextRow('s4', 'assistant', 40, MARKDOWN_REPLY),
    previewRow('s5', 'tool', 50, [
      previewCall('apply_patch', { input: PATCH_RESULT }),
      previewResult('Applied 1 hunk to packages/shared/session-chat-presentation/transcript.ts'),
    ]),
    previewRow('s6', 'tool', 60, [
      previewCall('Bash', { command: 'bun run typecheck' }),
      previewResult('error TS2322: Type "string | undefined" is not assignable to type "string".', true),
    ]),
  ];
}

function baseSnapshot(): GxserverReadSessionChatResult {
  return {
    messages: transcript(),
    hasMore: false,
    beforeOffset: 0,
    epoch: 1,
    seq: 1,
    status: 'ready',
    agent: 'codex',
    sessionAgentId: 'codex',
    agentSessionId: 'gx-synthetic',
    screenProbed: true,
    working: false,
    selectedOptions: {
      detectedAt: previewStamp(0),
      model: { value: 'gpt-5', label: 'GPT 5' },
      effort: { value: 'high', label: 'High' },
    },
    queue: [],
  };
}

/* ----------------------------------------------------------------------------------- the script */

interface Step {
  /** A short label for the report; it never names a record's contents. */
  label: string;
  run(): Promise<void> | void;
}

async function main(): Promise<number> {
  const world = new SyntheticWorld();
  const host = await loadChatBrain(world);

  const backend = new ChatPreviewBackend({ ...DEFAULT_CHAT_PREVIEW, scenario: 'conversation' });
  backend.snapshot = baseSnapshot();

  let revision = 0;
  let subscribed = false;

  /**
   * Everything the host hands the brain crosses as JSON in the real app, so the generator
   * copies it the same way. Without this the brain would share the answer table's own mutable
   * objects, and a replay, whose values come back through the recording, would drift from the
   * run that produced it.
   */
  const crossing = <T>(value: T): T => JSON.parse(JSON.stringify(value ?? null)) as T;

  /**
   * Feeds one server frame, the shape `SessionChatSocket` delivers, and then lets the promise
   * work it started finish. The engine's host does the same (it pumps its job queue after every
   * call), and a replay feeds one record at a time, so a frame that is not settled here would
   * have its continuations attributed to whatever call came next.
   */
  const publish = async (): Promise<void> => {
    if (!subscribed) return;
    backend.snapshot.seq += 1;
    host.event(
      crossing({
        ...backend.snapshot,
        type: 'sessionChatSnapshot',
        protocolVersion: 1,
        serverId: 'gx-synthetic',
        projectId: PROJECT_ID,
        sessionId: SESSION_ID,
      })
    );
    await settle();
  };

  /**
   * One turn of the host loop: fire due timers, take the document, answer every request the
   * brain raised. Repeats until the brain stops asking, the way the runtime thread does.
   */
  const pump = async (rounds = 24): Promise<void> => {
    let quiet = 0;
    for (let round = 0; round < rounds; round += 1) {
      host.tick();
      await settle();
      const document = host.take(revision);
      await settle();
      const parsed = JSON.parse(document) as { revision?: number; requests?: HostRequest[] };
      if (typeof parsed.revision === 'number') revision = parsed.revision;
      const requests = parsed.requests ?? [];
      // A request answered here can start the next one a microtask later, so the loop stops
      // only after two quiet rounds rather than the first.
      if (!requests.length) {
        quiet += 1;
        if (quiet > 1) return;
        continue;
      }
      quiet = 0;
      for (const request of requests) await answer(request);
      await settle();
    }
  };

  /**
   * A user action, the way the app issues one: queued at the brain and never waited for. The
   * work it starts is finished by the requests `pump` answers, so awaiting it here would
   * deadlock on the very request this loop is about to serve.
   */
  const act = (command: Record<string, unknown>): void => {
    void Promise.resolve(host.action(command)).catch(() => {
      // A refused action is part of the recording; the rules report it through the document.
    });
  };

  interface HostRequest {
    id?: number;
    kind: string;
    method: string;
    params: Record<string, unknown>;
  }

  const answer = async (request: HostRequest): Promise<void> => {
    if (request.kind === 'broker' && request.method === 'subscribe') {
      subscribed = true;
      await publish();
      return;
    }
    if (request.kind === 'broker' && request.method === 'unsubscribe') {
      subscribed = false;
      return;
    }
    if (request.id === undefined) return;
    try {
      let value: unknown;
      if (request.kind === 'rpc') value = await world.outside(() => backend.rpc(request.method, request.params));
      else if (request.method === 'composer') {
        const composer = (request.params.composer ?? {}) as Record<string, unknown> & { operation: string };
        const { operation, ...rest } = composer;
        value = await world.outside(() => composerAnswer(backend, operation, rest));
      } else return;
      host.resolve(request.id, crossing(value));
    } catch (error) {
      host.resolve(request.id, undefined, {
        message: error instanceof Error ? error.message : String(error),
        endpoint: request.method,
      });
    }
    await settle();
  };

  const steps: Step[] = [
    {
      label: 'boot',
      run: async () => {
        host.start({ clientId: 'gx-synthetic-client', projectId: PROJECT_ID });
        await settle();
        await pump();
      },
    },
    {
      label: 'stream the agent reply in pieces',
      run: async () => {
        // The rules see a growing last message, which is what a live reply looks like.
        const full = backend.snapshot.messages;
        const streamed = full.slice(0, 3);
        for (const cut of [0.3, 0.7, 1]) {
          const text = MARKDOWN_REPLY.slice(0, Math.ceil(MARKDOWN_REPLY.length * cut));
          backend.snapshot.messages = [...streamed, previewTextRow('s4', 'assistant', 40, text)];
          backend.snapshot.working = cut < 1;
          await publish();
          await pump();
        }
        backend.snapshot.messages = full;
        backend.snapshot.working = false;
        await publish();
        await pump();
      },
    },
    {
      label: 'a question with options',
      run: async () => {
        backend.snapshot.prompt = {
          kind: 'question',
          questions: [
            {
              question: 'Which part should we review next?',
              header: 'Next step',
              multiSelect: false,
              options: [
                { label: 'Layout', description: 'Compare spacing and typography.' },
                { label: 'Composer', description: 'Try typing and keyboard controls.' },
              ],
            },
          ],
        };
        await publish();
        await pump();
        act({ type: 'questionOption', index: 1 });
        await settle();
        await pump();
      },
    },
    {
      label: 'an approval',
      run: async () => {
        backend.snapshot.prompt = { kind: 'approval', tool: 'Shell', summary: 'bun run typecheck' };
        await publish();
        await pump();
        act({ type: 'answer', answer: { kind: 'approval', approved: true } });
        await settle();
        await pump();
      },
    },
    {
      label: 'a queued message',
      run: async () => {
        act({
          type: 'queue',
          text: 'Check the narrow layout next.',
          draftVersion: { draftId: 'gx-synthetic-draft', revision: 1 },
        });
        await settle();
        await pump();
      },
    },
    {
      label: 'an error notice',
      run: async () => {
        backend.snapshot.terminalNotice = {
          kind: 'updatePrompt',
          severity: 'error',
          source: 'screen',
          detectedAt: previewStamp(120),
          title: 'Codex could not reach the model.',
          detail: 'The request failed before the reply started. Try again, or choose another model.',
          choices: ['Try again', 'Dismiss'].map((label, index) => ({ index, label, selected: index === 0 })),
          screenTail: 'error: request failed (503)',
        };
        await publish();
        await pump();
        act({ type: 'dismissNotice' });
        await settle();
        await pump();
      },
    },
    {
      label: 'composer and transcript queries',
      run: async () => {
        act({ type: 'composerSelection', text: 'Look at @src/chat.ts next', caret: 24 });
        await settle();
        await pump();
        (host.composerReferences as (text: string) => unknown)('Look at src/chat.ts:12 next');
        (host.referenceMenu as (href: string) => unknown)('file:///sample/project/src/chat.ts');
        (host.transcriptMenu as (request: unknown) => unknown)({
          href: null,
          selection: 'normalizeChatTranscript',
          questionActive: false,
        });
        (host.sendBlockedToast as (reason: string) => unknown)('terminalChoicePending');
        await settle();
        await pump();
      },
    },
    {
      label: 'view settings',
      run: async () => {
        act({ type: 'toggleSummary' });
        await settle();
        await pump();
        act({ type: 'setVerbose', enabled: true });
        await settle();
        await pump();
      },
    },
  ];

  for (const step of steps) await step.run();
  // One last document, so the recording ends on a published state rather than an input.
  await pump();
  world.flush();

  mkdirSync(RECORDING_ROOT, { recursive: true, mode: 0o700 });
  const path = `${RECORDING_ROOT}/synthetic.jsonl`;
  const body = [serializeHeader(CLOCK_START), ...world.lines].join('\n');
  writeFileSync(path, `${body}\n`, { mode: 0o600 });

  const documents = world.lines.filter((line) => line.includes('"k":"doc"')).length;
  const queries = world.lines.filter((line) => line.includes('"k":"query"')).length;
  console.log(`steps       ${steps.length}`);
  console.log(`records     ${world.lines.length} (${documents} documents, ${queries} queries)`);
  console.log(`fingerprint ${nativeChatReplayHash(body)}`);
  console.log(`recording   ${path}`);
  return world.lines.length && documents ? 0 : 1;
}

process.exitCode = await main();
